# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20171128_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Account'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
